---
- name: install packages
  packages:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - vim
      - tmux
      - curl
      - ca-certificates
      - gnupg
      - lsb-release
      - fzf
      - nodejs
      - npm
      - jq
      - stow
      - xclip

- name: install docker
  shell: "curl -fsSL https://get.docker.com | sudo bash"
  register: install_docker
